### ISSUE TITLE
cc: error: sdl2-config: No such file or directory

### ISSUE THREAD

**Issue by darkoverlordofdata** [nsauzede/vsdl2#7]
I'm running debian buster.

Your code is missing the linux backtick (command substitution) symbole. I modified line 7 from

#flag linux sdl2-config --cflags --libs  -lSDL2_ttf -lSDL2_mixer -lSDL2_image

to 

#flag linux `sdl2-config --cflags --libs`  -lSDL2_ttf -lSDL2_mixer -lSDL2_image

and it works as expected.

**Comment by nsauzede** [comment]
yeah sorry about that; can you confirm that the latest V master works with sdl in debian buster now ?
